workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    environment:
      groups:
        - android_credentials
      vars:
        PACKAGE_NAME: "com.bizzotto.bitto"
    scripts:
      - name: Build Android App Bundle (AAB)
        script: |
          gradle bundleRelease
      - name: Build APK Release
        script: |
          gradle assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - tu_correo@example.com
        notify:
          success: true
          failure: true
